import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Clock3, Dice5, Edit3, Flame, ImagePlus, Plus, Play, Search, Sparkles, Square, Trophy, Trash2, X } from 'lucide-react';
import { PROJECTS, SAMPLE_SESSIONS, type CreativeProject, type ProjectSession, type ProjectStatus } from '@/data/projects';

type DetailTab = 'Overview'|'Tasks'|'Notes'|'Gallery'|'Supplies/Parts'|'Project Log';
type DecideMode = 'Quick Win'|'Resurrect'|'Current Obsession'|'$0 Mode'|'Easy Setup'|'Random';
type ActiveSession = {projectId:string; intention:string; startedAt:number};
const DETAIL_TABS: DetailTab[]=['Overview','Tasks','Notes','Gallery','Supplies/Parts','Project Log'];
const MODES: DecideMode[]=['Quick Win','Resurrect','Current Obsession','$0 Mode','Easy Setup','Random'];
const ORACLE_LINES:Record<DecideMode,string[]>={
 'Quick Win':['A tiny triumph awaits.','No grand quest today. Just this.','I foresee satisfaction with minimal suffering.','Quickly now, before you change your mind.'],
 'Resurrect':['Something forgotten stirs beneath the cobwebs…','You wish to disturb the dead?','An old creation calls your name.','The graveyard is unusually restless today.'],
 'Current Obsession':['The loudest current is impossible to ignore.','Back to the thing currently haunting your thoughts.','The obsession has not released you yet.','Your favorite little problem awaits.'],
 '$0 Mode':['The coin purse remains sealed.','We shall conjure from what we already possess.','Creativity requires no tribute today.','Not one shiny coin shall leave your pocket.'],
 'Easy Setup':['Minimal preparation. The stars understand.','Your workspace shall remain mostly intact.','No seventeen-step setup ritual tonight.','A gentle quest with very little unpacking.'],
 'Random':['The stars have chosen. I accept no complaints.','Do not blame me. Blame fate.','Interesting. Even I did not expect that.','I shuffled the currents. This surfaced.']
};
type Achievement = {id:string; icon:string; name:string; description:string; requirement:string; earned:boolean; secret?:boolean};
const ACHIEVEMENTS: Achievement[]=[
  {id:'first-spark',icon:'★',name:'FIRST SPARK',description:'You turned an idea into something real and started your creative archive.',requirement:'Create your first project.',earned:true},
  {id:'mix-maker',icon:'♫',name:'MIX MAKER',description:'A little soundtrack-making magic made its way into the archive.',requirement:'Create or complete a music / mix project.',earned:true},
  {id:'hyperfocus',icon:'✦',name:'HYPERFOCUS',description:'You followed one creative current long enough to disappear into it.',requirement:'Log a creative session of 90 minutes or longer.',earned:true},
  {id:'night-diver',icon:'☾',name:'NIGHT DIVER',description:'The archive caught you making things while the rest of the world was asleep.',requirement:'Log creative activity after 3:00 AM.',earned:false},
  {id:'resurrector',icon:'♜',name:'RESURRECTOR',description:'You brought an old project back from the depths instead of abandoning it forever.',requirement:'Return to a project after 30+ days away.',earned:false},
  {id:'zero-dollar',icon:'◇',name:'ZERO-DOLLAR MAGIC',description:'You made something without buying a single new thing.',requirement:'Complete a project using only supplies you already own.',earned:false},
];
const statusLabel:Record<ProjectStatus,string>={obsession:'CURRENT OBSESSION',active:'ACTIVE PROJECTS',idea:'IDEA VAULT',completed:'COMPLETED / ARCHIVED',graveyard:'PROJECT GRAVEYARD'};
const storageKey='ally-archive-projects-v13';
const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;

function loadProjects(){
  try { const raw=localStorage.getItem(storageKey); return raw ? (JSON.parse(raw) as any[]).map(p=>({...p,setup:p.setup||(p.mess==='messy'?'workstation':p.mess==='none'?'grab-go':'light')})) as CreativeProject[] : PROJECTS; }
  catch { return PROJECTS; }
}
function saveProjects(projects:CreativeProject[]){ try{ localStorage.setItem(storageKey,JSON.stringify(projects)); }catch{} }

const SETUP_LABELS:Record<string,string>={'grab-go':'GRAB & GO','light':'LIGHT SETUP','workstation':'WORKSTATION','takeover':'TAKE OVER THE ROOM'};
const CATEGORY_OPTIONS=['TECH + ART','BUILD / TECH','ART / DESIGN','MUSIC','JOURNAL','JOURNAL / WRITING','CRAFT / CUSTOMIZE','DECOR','DISPLAY','DISPLAY / ORGANIZE','EXPERIMENT','OTHER'];
const ICON_OPTIONS=[['⚒','TOOLS'],['♫','MUSIC'],['✎','PENCIL'],['✦','SPARKLE'],['▤','PAGES'],['⚗','FLASK'],['◆','GEM'],['●','DISC'],['★','STAR'],['🐙','OCTOPUS'],['🪼','JELLYFISH'],['🐠','FISH'],['🐡','PUFFERFISH'],['🦀','CRAB'],['⭐','STARFISH'],['🐢','SEA TURTLE'],['🦦','OTTER'],['🐳','WHALE'],['🦈','SHARK'],['🐬','DOLPHIN'],['🐚','SHELL']];
const categoryIcon=(category:string)=>{const c=category.toUpperCase();if(c.includes('TECH')||c.includes('BUILD')||c.includes('HARDWARE'))return '⚒';if(c.includes('MUSIC'))return '♫';if(c.includes('JOURNAL')||c.includes('WRITE'))return '✎';if(c.includes('ART')||c.includes('DESIGN')||c.includes('DECOR')||c.includes('CRAFT'))return '✦';if(c.includes('DISPLAY')||c.includes('ORGAN'))return '▤';if(c.includes('EXPERIMENT'))return '⚗';return '◆'};

function Meta({project}:{project:CreativeProject}){
  return <div className="project-meta">
    <span>ENERGY <strong>{project.energy.toUpperCase()}</strong></span><span>SETUP <strong>{SETUP_LABELS[project.setup]||'LIGHT SETUP'}</strong></span><span>TIME <strong>~{project.estimatedMinutes} MIN</strong></span><span>TYPE <strong>{project.category}</strong></span><span>COST <strong>${project.cost}</strong></span>
  </div>
}
function ProjectCard({project,onOpen}:{project:CreativeProject;onOpen:(p:CreativeProject)=>void}){
  const done=project.tasks.filter(t=>t.done).length, pct=Math.round(done/Math.max(project.tasks.length,1)*100);
  const cobwebbed=project.status!=='graveyard' && !!project.lastTouchedAt && Date.now()-project.lastTouchedAt>=14*86400000;
  return <button className={`project-card project-${project.color} ${cobwebbed?'is-cobwebbed':''}`} onClick={()=>onOpen(project)}>
    {cobwebbed&&<span className="project-cobweb" aria-label="Untouched for 14 days">🕸</span>}<div className="project-card-top"><span className="project-icon" title={`${project.category} project`}><b>{project.icon || categoryIcon(project.category)}</b><small>{project.category}</small></span><span className="project-status">{project.status==='completed'?'ARCHIVED':project.status.toUpperCase()}</span></div>
    <h4>{project.title}</h4><p>{project.tagline}</p><Meta project={project}/>
    <div className="card-next-step"><small>NEXT STEP</small><span>{project.tasks.find(t=>!t.done)?.title || (project.tasks.length ? 'All tasks complete — treasure finished!' : 'Add the first task')}</span></div>
    <div className="progress-readout"><b>{project.tasks.length ? `${done} of ${project.tasks.length}` : '—'}</b><span>{project.tasks.length ? 'TASKS FINISHED' : 'NO TASKS YET'}</span></div>
    <div className="project-progress" aria-label={`${done} of ${project.tasks.length} tasks complete`}><i style={{width:`${pct}%`}}/></div>
  </button>
}

function GraveyardStone({project,onOpen}:{project:CreativeProject;onOpen:(p:CreativeProject)=>void}){
  return <button className="grave-plot" onClick={()=>onOpen(project)} aria-label={`Open memorial for ${project.title}`}>
    <span className="grave-moonlight"/><span className="grave-grass grass-left"/><span className="grave-grass grass-right"/><span className="grave-flowers">✿ · ✦</span>
    <span className="graveyard-stone"><span className="stone-symbol">{project.icon || categoryIcon(project.category)}</span><small>HERE LIES</small><b>{project.title}</b></span>
    <span className="grave-soil"/>
  </button>;
}

function ProjectEditor({project,onSave,onClose}:{project?:CreativeProject;onSave:(p:CreativeProject)=>void;onClose:()=>void}){
  const isNew=!project;
  return <div className="session-modal"><form className="project-editor" onSubmit={e=>{
    e.preventDefault(); const fd=new FormData(e.currentTarget);
    const next:CreativeProject={
      id:project?.id||uid('project'), title:String(fd.get('title')||'Untitled Project'), tagline:String(fd.get('tagline')||''),
      status:String(fd.get('status')) as ProjectStatus, category:String(fd.get('category')||'OTHER').toUpperCase(),
      energy:String(fd.get('energy')) as CreativeProject['energy'], setup:String(fd.get('setup')) as CreativeProject['setup'],
      estimatedMinutes:Number(fd.get('estimatedMinutes'))||30, cost:Number(fd.get('cost'))||0,
      color:String(fd.get('color')) as CreativeProject['color'], icon:String(fd.get('icon')||categoryIcon(String(fd.get('category')||'OTHER'))), overview:String(fd.get('overview')||''),
      tasks:project?.tasks||[], notes:project?.notes||[], gallery:project?.gallery||[], supplies:project?.supplies||[], log:project?.log||[], lastTouchedAt:project?.lastTouchedAt||Date.now(), abandonedAt:project?.abandonedAt
    }; onSave(next);
  }}>
    <button type="button" className="modal-close" onClick={onClose}><X/></button><span className="modal-shell">{isNew?'✦':'✎'}</span><small>{isNew?'NEW TREASURE':'EDIT PROJECT'}</small><h2>{isNew?'BEGIN A PROJECT':'RESHAPE THIS PROJECT'}</h2>
    <div className="editor-grid">
      <label>Project name<input name="title" required defaultValue={project?.title}/></label><label>Short vibe<input name="tagline" defaultValue={project?.tagline}/></label>
      <label>Status<select name="status" defaultValue={project?.status||'active'}><option value="obsession">CURRENT OBSESSION</option><option value="active">ACTIVE</option><option value="idea">IDEA VAULT</option><option value="completed">COMPLETED / ARCHIVED</option></select></label>
      <label>Category<select name="category" defaultValue={project?.category||'CRAFT / CUSTOMIZE'}>{CATEGORY_OPTIONS.map(c=><option key={c} value={c}>{c}</option>)}</select></label>
      <label>Pixel symbol<select name="icon" defaultValue={project?.icon||categoryIcon(project?.category||'OTHER')}>{ICON_OPTIONS.map(([symbol,name])=><option key={name} value={symbol}>{symbol}  {name}</option>)}</select></label>
      <label>Energy<select name="energy" defaultValue={project?.energy||'medium'}><option value="low">LOW</option><option value="medium">MEDIUM</option><option value="high">HIGH</option></select></label>
      <label>Setup<select name="setup" defaultValue={project?.setup||'light'}><option value="grab-go">GRAB & GO</option><option value="light">LIGHT SETUP</option><option value="workstation">WORKSTATION</option><option value="takeover">TAKE OVER THE ROOM</option></select></label>
      <label>Estimated minutes<input type="number" min="1" name="estimatedMinutes" defaultValue={project?.estimatedMinutes||30}/></label><label>Cost<input type="number" min="0" step="1" name="cost" defaultValue={project?.cost||0}/></label>
      
      <label className="color-field">Panel color<select name="color" defaultValue={project?.color||'pink'}><option value="pink">PEARL PINK</option><option value="coral">CORAL PEACH</option><option value="gold">TREASURE GOLD</option><option value="blue">LAGOON BLUE</option><option value="seafoam">SEAFOAM</option><option value="lavender">SHELL LAVENDER</option><option value="kelp">KELP GREEN</option><option value="midnight">MIDNIGHT TIDE</option><option value="jelly">JELLYFISH PURPLE</option><option value="seaglass">SEA GLASS</option></select><span className="color-swatches" aria-hidden="true"><i className="swatch-pink"/><i className="swatch-coral"/><i className="swatch-gold"/><i className="swatch-blue"/></span></label>
      <label className="editor-wide">What are we making?<textarea name="overview" defaultValue={project?.overview}/></label>
    </div><button className="begin-session">{isNew?<><Plus/> ADD TO ARCHIVE</>:<><Edit3/> SAVE CHANGES</>}</button>
  </form></div>
}

function Detail({project,onBack,onStart,onChange,onEdit,onAbandon,onResurrect,isSessionActive}:{project:CreativeProject;onBack:()=>void;onStart:(p:CreativeProject)=>void;onChange:(p:CreativeProject)=>void;onEdit:()=>void;onAbandon:()=>void;onResurrect:()=>void;isSessionActive:boolean}){
  const[tab,setTab]=useState<DetailTab>('Overview'),[editingLogId,setEditingLogId]=useState<string|null>(null);
  const patch=(p:Partial<CreativeProject>)=>onChange({...project,...p});
  const addTask=(title:string)=>title.trim()&&patch({tasks:[...project.tasks,{id:uid('task'),title:title.trim(),done:false}]});
  const addNote=(note:string)=>note.trim()&&patch({notes:[...project.notes,note.trim()]});
  const addSupply=(name:string,owned:boolean,cost:number)=>name.trim()&&patch({supplies:[...project.supplies,{id:uid('supply'),name:name.trim(),owned,cost:owned?undefined:cost}]});
  const addImage=(file?:File)=>{ if(!file)return; const reader=new FileReader(); reader.onload=()=>patch({gallery:[...project.gallery,{id:uid('img'),name:file.name,dataUrl:String(reader.result)}]}); reader.readAsDataURL(file); };
  const done=project.tasks.filter(t=>t.done).length, pct=Math.round(done/Math.max(project.tasks.length,1)*100);
  return <div className="project-detail animate-fade-in">
    <div className="detail-topline"><button className="lab-back" onClick={onBack}><ArrowLeft/> PROJECT SHELF</button><div className="detail-actions"><button className="edit-project-button" onClick={onEdit}><Edit3/> EDIT PROJECT</button>{project.status==='graveyard'?<button className="resurrect-button" onClick={onResurrect}>⚡ RESURRECT PROJECT</button>:<button className="abandon-button" onClick={onAbandon}>☠ ABANDON PROJECT</button>}</div></div>
    <section className={`detail-hero project-${project.color} ${project.status==='graveyard'?'memorial-hero':''}`}>{project.status==='graveyard'?<div className="memorial-title"><span className="memorial-stone">🪦</span><small>HERE LIES</small><h2>{project.title}</h2><p>Abandoned {project.abandonedAt?new Date(project.abandonedAt).toLocaleDateString(): 'to the deep'}</p><em>“{project.tagline}”</em></div>:<><div className="detail-title"><span className="detail-category-icon">{project.icon || categoryIcon(project.category)}</span><div><small>{project.category} · {statusLabel[project.status]}</small><h2>{project.title}</h2><p>{project.tagline}</p></div></div><button className={`session-button ${isSessionActive?'is-running':''}`} onClick={()=>!isSessionActive&&onStart(project)} disabled={isSessionActive}>{isSessionActive?<><span className="session-live-dot"/> SESSION ACTIVE</>:<><Play/> START CREATIVE SESSION</>}</button><Meta project={project}/></>}</section>
    <nav className="detail-tabs">{DETAIL_TABS.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><section className="detail-content">
    {tab==='Overview'&&<><h3>PROJECT SPELL</h3><p>{project.overview}</p><div className="overview-grid"><div><b>NEXT TINY STEP</b><span>{project.tasks.find(t=>!t.done)?.title||'Celebrate this finished treasure!'}</span></div><div><b>PROJECT PROGRESS</b><strong className="big-progress">{project.tasks.length ? `${done} of ${project.tasks.length}` : 'NO TASKS'}</strong><span>{project.tasks.length ? 'tasks finished' : 'Add a task to start tracking progress'}</span><div className="project-progress overview-progress"><i style={{width:`${pct}%`}}/></div></div></div></>}
    {tab==='Tasks'&&<><div className="section-heading"><h3>QUEST LIST</h3><QuickAdd placeholder="ADD A NEW QUEST..." button="ADD QUEST" onAdd={addTask}/></div>{project.tasks.map(t=><label className="task-row" key={t.id}><input type="checkbox" checked={t.done} onChange={()=>patch({tasks:project.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)})}/><span>{t.title}</span><button type="button" className="tiny-delete" onClick={e=>{e.preventDefault();patch({tasks:project.tasks.filter(x=>x.id!==t.id)})}}>×</button></label>)}</>}
    {tab==='Notes'&&<><div className="section-heading"><h3>SCATTERED PEARLS</h3><QuickAdd placeholder="TUCK AWAY A NOTE..." button="ADD NOTE" onAdd={addNote}/></div>{project.notes.map((n,i)=><div className="note-card" key={i}>✦ {n}<button className="tiny-delete" onClick={()=>patch({notes:project.notes.filter((_,j)=>j!==i)})}>×</button></div>)}</>}
    {tab==='Gallery'&&<><div className="gallery-heading"><div><h3>MEMORY SHELLS</h3><p>Photos stay on this device.</p></div><label className="image-add-button"><ImagePlus/> ADD IMAGE<input type="file" accept="image/*" onChange={e=>{addImage(e.target.files?.[0]);e.currentTarget.value=''}}/></label></div><div className="gallery-grid">{project.gallery.length?project.gallery.map(g=><div className={g.dataUrl?'has-image':''} key={g.id}>{g.dataUrl?<img src={g.dataUrl} alt={g.name}/>:<span>✧</span>}<small>{g.name}</small><button className="image-remove" onClick={()=>patch({gallery:project.gallery.filter(x=>x.id!==g.id)})}>×</button></div>):<p>No snapshots tucked away yet.</p>}</div><p className="storage-note">Prototype note: images are saved in this browser. On the physical cyberdeck, this same action can copy the file into local project storage.</p></>}
    {tab==='Supplies/Parts'&&<><div className="section-heading"><h3>SUPPLY CHEST</h3><SupplyAdd onAdd={addSupply}/></div>{project.supplies.map((s,i)=><div className="supply-row" key={s.id||i}><button className="owned-toggle" onClick={()=>patch({supplies:project.supplies.map((x,j)=>j===i?{...x,owned:!x.owned}:x)})}>{s.owned?'◆':'◇'}</button><span>{s.name}</span><span>{s.owned?'IN STASH':`$${s.cost||0}`}</span><button className="tiny-delete" onClick={()=>patch({supplies:project.supplies.filter((_,j)=>j!==i)})}>×</button></div>)}</>}
    {tab==='Project Log'&&<><div className="section-heading"><h3>CAPTAIN'S LOG</h3><p className="log-helper">Test entries can be edited or tossed overboard.</p></div>{project.log.length?project.log.map(l=><div className={`log-row ${editingLogId===l.id?'is-editing':''}`} key={l.id}>{editingLogId===l.id?<><input aria-label="Log date" value={l.date} onChange={e=>patch({log:project.log.map(x=>x.id===l.id?{...x,date:e.target.value}:x)})}/><textarea aria-label="Log note" value={l.note} onChange={e=>patch({log:project.log.map(x=>x.id===l.id?{...x,note:e.target.value}:x)})}/><input className="log-minutes" type="number" min="0" aria-label="Minutes" value={l.minutes||''} onChange={e=>patch({log:project.log.map(x=>x.id===l.id?{...x,minutes:Number(e.target.value)||undefined}:x)})}/></>:<><b>{l.date}</b><span>{l.note}</span><small>{l.minutes?`${l.minutes} MIN`:''}</small></>}<div className="log-actions"><button onClick={()=>setEditingLogId(editingLogId===l.id?null:l.id)}><Edit3/> {editingLogId===l.id?'DONE':'EDIT'}</button><button className="log-delete" onClick={()=>patch({log:project.log.filter(x=>x.id!==l.id)})}><Trash2/> DELETE</button></div></div>):<p>The tide is quiet. Your first session will start the log.</p>}</>}
    </section></div>
}

function PixelWizard({mood='wise',face=0}:{mood?:'wise'|'excited'|'oracle';face?:number}){const sprites=['idle','happy','cast','jump','think','grumpy'];return <div className={`pixel-wizard wizard-${mood} wizard-image`} aria-hidden="true"><img src={`/assets/wizard_${sprites[face%sprites.length]}.png`} alt="" draggable={false}/><span className="wizard-magic-flare">✦</span></div>}
function NewProjectWizard({onSave,onClose}:{onSave:(p:CreativeProject)=>void;onClose:()=>void}){
 const[step,setStep]=useState(0),[draft,setDraft]=useState<any>({title:'',tagline:'',category:'CRAFT / CUSTOMIZE',icon:'🐙',energy:'medium',setup:'light',estimatedMinutes:30,cost:0,color:'lavender',overview:''});
 const patch=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
 const finish=()=>onSave({id:uid('project'),title:draft.title||'Untitled Treasure',tagline:draft.tagline||'A new current in the archive',status:'active',category:draft.category,energy:draft.energy,setup:draft.setup,estimatedMinutes:Number(draft.estimatedMinutes)||30,cost:Number(draft.cost)||0,color:draft.color,icon:draft.icon,overview:draft.overview||draft.tagline||'A new project waiting to become something.',tasks:[],notes:[],gallery:[],supplies:[],log:[],lastTouchedAt:Date.now()});
 const pages=[
  <><h2>WHAT ARE WE MAKING?</h2><p>“Every treasure needs a name.”</p><input autoFocus value={draft.title} onChange={e=>patch('title',e.target.value)} placeholder="PROJECT NAME..."/><input value={draft.tagline} onChange={e=>patch('tagline',e.target.value)} placeholder="A SHORT VIBE..."/></>,
  <><h2>WHAT KIND OF MAGIC?</h2><p>“Choose its realm — and a little guardian.”</p><label>Category<select value={draft.category} onChange={e=>patch('category',e.target.value)}>{CATEGORY_OPTIONS.map(c=><option key={c}>{c}</option>)}</select></label><label>Pixel symbol<select value={draft.icon} onChange={e=>patch('icon',e.target.value)}>{ICON_OPTIONS.map(([i,n])=><option key={n} value={i}>{i}  {n}</option>)}</select></label></>,
  <><h2>HOW BIG IS THE QUEST?</h2><p>“I shall not send you into a workshop when you wanted a tiny spell.”</p><label>Energy<select value={draft.energy} onChange={e=>patch('energy',e.target.value)}><option value="low">LOW</option><option value="medium">MEDIUM</option><option value="high">HIGH</option></select></label><label>Setup<select value={draft.setup} onChange={e=>patch('setup',e.target.value)}><option value="grab-go">GRAB & GO</option><option value="light">LIGHT SETUP</option><option value="workstation">WORKSTATION</option><option value="takeover">TAKE OVER THE ROOM</option></select></label><label>Estimated minutes<input type="number" value={draft.estimatedMinutes} onChange={e=>patch('estimatedMinutes',e.target.value)}/></label></>,
  <><h2>CHOOSE ITS COLORS</h2><p>“A proper treasure should be recognizable at a glance.”</p><label>Panel color<select value={draft.color} onChange={e=>patch('color',e.target.value)}>{[['pink','PEARL PINK'],['coral','CORAL PEACH'],['gold','TREASURE GOLD'],['blue','LAGOON BLUE'],['seafoam','SEAFOAM'],['lavender','SHELL LAVENDER'],['kelp','KELP GREEN'],['midnight','MIDNIGHT TIDE'],['jelly','JELLYFISH PURPLE'],['seaglass','SEA GLASS']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Estimated cost<input type="number" min="0" value={draft.cost} onChange={e=>patch('cost',e.target.value)}/></label><label>What are we making?<textarea value={draft.overview} onChange={e=>patch('overview',e.target.value)} placeholder="OPTIONAL — TELL THE WIZARD MORE..."/></label></>
 ];
 return <div className="session-modal wizard-modal"><div className="wizard-card"><button className="modal-close" onClick={onClose}><X/></button><div className="wizard-character"><PixelWizard mood={step===0?'excited':'wise'} face={step%6}/><b>MASTER OF THE PROJECT LAB</b></div>{pages[step]}<div className="wizard-nav">{step>0&&<button onClick={()=>setStep(step-1)}>← BACK</button>}<button className="wizard-next" disabled={step===0&&!draft.title.trim()} onClick={()=>step===pages.length-1?finish():setStep(step+1)}>{step===pages.length-1?'✦ CREATE TREASURE':'NEXT →'}</button></div></div></div>
}

function QuickAdd({placeholder,button,onAdd}:{placeholder:string;button:string;onAdd:(v:string)=>void}){const[v,setV]=useState('');return <form className="quick-add" onSubmit={e=>{e.preventDefault();onAdd(v);setV('')}}><input value={v} onChange={e=>setV(e.target.value)} placeholder={placeholder}/><button><Plus/> {button}</button></form>}
function SupplyAdd({onAdd}:{onAdd:(name:string,owned:boolean,cost:number)=>void}){const[name,setName]=useState(''),[owned,setOwned]=useState(true),[cost,setCost]=useState('');return <form className="supply-add" onSubmit={e=>{e.preventDefault();onAdd(name,owned,Number(cost)||0);setName('');setCost('')}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="NEW MATERIAL / PART..."/><label><input type="checkbox" checked={owned} onChange={e=>setOwned(e.target.checked)}/> IN STASH</label>{!owned&&<input className="cost-field" type="number" min="0" placeholder="$" value={cost} onChange={e=>setCost(e.target.value)}/>}<button><Plus/> ADD</button></form>}

export default function LabView(){
 const[projects,setProjects]=useState<CreativeProject[]>(loadProjects),[selectedId,setSelectedId]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|ProjectStatus>('all'),[decision,setDecision]=useState<CreativeProject|null>(null),[sessionProject,setSessionProject]=useState<CreativeProject|null>(null),[activeSession,setActiveSession]=useState<ActiveSession|null>(null),[now,setNow]=useState(Date.now()),[sessions,setSessions]=useState<ProjectSession[]>(SAMPLE_SESSIONS),[editing,setEditing]=useState<CreativeProject|undefined|null>(null),[selectedAchievement,setSelectedAchievement]=useState<Achievement|null>(null),[newWizard,setNewWizard]=useState(false),[oracleLine,setOracleLine]=useState('Ask the currents. I shall interpret.'),[abandoningId,setAbandoningId]=useState<string|null>(null),[wizardCast,setWizardCast]=useState(0),[wizardFace,setWizardFace]=useState(0);
 useEffect(()=>{if(!activeSession)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[activeSession]);
 const selected=projects.find(p=>p.id===selectedId)||null;
 const updateProjects=(next:CreativeProject[])=>{setProjects(next);saveProjects(next)};
 const upsert=(project:CreativeProject)=>{const exists=projects.some(p=>p.id===project.id);updateProjects(exists?projects.map(p=>p.id===project.id?project:p):[project,...projects]);setEditing(null);setSelectedId(project.id)};
 const change=(project:CreativeProject)=>updateProjects(projects.map(p=>p.id===project.id?project:p));
 const filtered=useMemo(()=>projects.filter(p=>(filter==='all'||p.status===filter)&&(`${p.title} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[projects,filter,query]),totalMinutes=sessions.reduce((a,s)=>a+s.minutes,0);
 const decide=(mode:DecideMode)=>{setWizardCast(n=>n+1);setWizardFace(n=>{const expressive=[1,2,3,4,5];let next=expressive[Math.floor(Math.random()*expressive.length)];if(next===n)next=expressive[(expressive.indexOf(next)+1)%expressive.length];return next});let pool=projects.filter(p=>p.status!=='completed'&&p.status!=='graveyard');if(mode==='Quick Win')pool=pool.filter(p=>p.estimatedMinutes<=30);if(mode==='Resurrect')pool=projects.filter(p=>p.status==='graveyard');if(mode==='Current Obsession')pool=projects.filter(p=>p.status==='obsession');if(mode==='$0 Mode')pool=pool.filter(p=>p.cost===0||p.supplies.every(s=>s.owned));if(mode==='Easy Setup')pool=pool.filter(p=>p.setup==='grab-go'||p.setup==='light');const choices=pool.length?pool:projects.filter(p=>p.status!=='completed');setDecision(choices[Math.floor(Math.random()*choices.length)]||projects[0]);const lines=ORACLE_LINES[mode];const fresh=lines.filter(line=>line!==oracleLine);setOracleLine((fresh.length?fresh:lines)[Math.floor(Math.random()*(fresh.length?fresh:lines).length)]);};
 const beginSession=(project:CreativeProject)=>{change({...project,lastTouchedAt:Date.now()});const intention=project.tasks.find(t=>!t.done)?.title||'Creative session';setActiveSession({projectId:project.id,intention,startedAt:Date.now()});setNow(Date.now());setSessionProject(null)};
 const finishActiveSession=()=>{if(!activeSession)return;const minutes=Math.max(1,Math.round((Date.now()-activeSession.startedAt)/60000));setSessions([{id:`local-${Date.now()}`,projectId:activeSession.projectId,date:'TODAY',minutes,intention:activeSession.intention},...sessions]);const current=projects.find(p=>p.id===activeSession.projectId);if(current)change({...current,lastTouchedAt:Date.now(),log:[{id:uid('log'),date:'TODAY',note:activeSession.intention,minutes},...current.log]});setActiveSession(null)};
 const elapsedSeconds=activeSession?Math.max(0,Math.floor((now-activeSession.startedAt)/1000)):0;
 const elapsedLabel=`${String(Math.floor(elapsedSeconds/60)).padStart(2,'0')}:${String(elapsedSeconds%60).padStart(2,'0')}`;
 if(selected)return <div className={abandoningId===selected.id?'project-death-transition':''}><Detail project={selected} onBack={()=>setSelectedId(null)} onStart={beginSession} onChange={change} onEdit={()=>setEditing(selected)} onAbandon={()=>{setAbandoningId(selected.id);window.setTimeout(()=>{change({...selected,status:'graveyard',abandonedAt:Date.now()});setAbandoningId(null)},850)}} onResurrect={()=>{change({...selected,status:'active',abandonedAt:undefined,lastTouchedAt:Date.now(),log:[{id:uid('log'),date:'TODAY',note:'Resurrected from the Project Graveyard.'},...selected.log]});}} isSessionActive={activeSession?.projectId===selected.id}/>{activeSession&&<div className="active-session-bar"><div className="session-live-dot"/><div className="active-session-copy"><small>CREATIVE SESSION RUNNING</small><b>{projects.find(p=>p.id===activeSession.projectId)?.title}</b><span>{activeSession.intention}</span></div><strong>{elapsedLabel}</strong><button onClick={finishActiveSession}><Square/> FINISH SESSION</button></div>}{editing&&<ProjectEditor project={editing} onSave={upsert} onClose={()=>setEditing(null)}/>} {abandoningId===selected.id&&<div className="death-overlay"><span>🪦</span><b>{selected.title}</b><small>HAS ENTERED THE GRAVEYARD</small></div>}</div>;
 return <div className="projects-workspace"><div className="lab-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SEARCH THE WORKBENCH..."/></label><div className="toolbar-actions"><button className="new-project-button" onClick={()=>setNewWizard(true)}><Plus/> NEW PROJECT</button><button className="session-launch-button" onClick={()=>setSessionProject(projects.find(p=>p.status==='obsession')||projects[0])}><Play/> START CREATIVE SESSION</button></div></div><div className="lab-filters">{(['all','obsession','active','idea','completed','graveyard'] as const).map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='all'?'ALL':f.toUpperCase()}</button>)}</div>
 {(['obsession','active','idea','completed','graveyard'] as ProjectStatus[]).map(status=>{const items=filtered.filter(p=>p.status===status);return items.length?<section className={`project-shelf shelf-${status}`} key={status}><header><span>{status==='obsession'?'✦':status==='active'?'≈':status==='idea'?'◇':status==='graveyard'?'🪦':'★'}</span><h3>{statusLabel[status]}</h3><small>{items.length} {items.length===1?'TREASURE':'TREASURES'}</small></header><div className={status==='graveyard'?'graveyard-grid':'project-card-grid'}>{items.map(p=>status==='graveyard'?<GraveyardStone key={p.id} project={p} onOpen={p=>setSelectedId(p.id)}/>:<ProjectCard key={p.id} project={p} onOpen={p=>setSelectedId(p.id)}/>)}</div></section>:null})}
 {!filtered.length&&<div className="empty-tide">No treasures surfaced. Try another current.</div>}
 <section className={`decide-panel wizard-oracle ${decision?'wizard-is-speaking':''}`}><div className="oracle-copy"><span className="oracle-title"><Dice5/><h3>DECIDE FOR ME</h3></span></div><div className="wizard-stage"><div className={`wizard-cast wizard-face-${wizardFace}`} key={wizardCast}><PixelWizard mood={decision?'excited':'oracle'} face={wizardFace}/></div>{decision&&<div className="wizard-speech" key={`${wizardCast}-${oracleLine}`}>“{oracleLine}”</div>}</div><div className="decide-buttons">{MODES.map(m=><button onClick={()=>decide(m)} key={m}>{m}</button>)}</div>{decision&&<button className="decision-result" onClick={()=>setSelectedId(decision.id)}><Sparkles/><span><small>THE WIZARD CHOSE</small><b>{decision.title}</b></span><small>OPEN PROJECT →</small></button>}</section>
 <div className="lab-bottom-grid"><section className="pulse-panel"><header><Flame/><h3>CREATIVE PULSE</h3></header><div className="stats-grid"><div><b>{projects.filter(p=>p.status==='active'||p.status==='obsession').length}</b><span>IN MOTION</span></div><div><b>{sessions.length}</b><span>SESSIONS</span></div><div><b>{Math.round(totalMinutes/60*10)/10}h</b><span>MAKING</span></div><div><b>{projects.reduce((a,p)=>a+p.tasks.filter(t=>t.done).length,0)}</b><span>QUESTS WON</span></div></div><div className="pulse-bars"><span>MUSIC<i style={{width:'82%'}}/></span><span>TECH + ART<i style={{width:'64%'}}/></span><span>JOURNAL<i style={{width:'38%'}}/></span></div></section><section className="achievement-panel"><header><Trophy/><h3>ACHIEVEMENTS</h3><small>{ACHIEVEMENTS.filter(a=>a.earned).length} / {ACHIEVEMENTS.length} FOUND</small></header><p className="achievement-hint">Tap a badge to see what it means.</p><div className="badge-grid">{ACHIEVEMENTS.map(a=><button key={a.id} className={a.earned?'earned':''} onClick={()=>setSelectedAchievement(a)}><b>{a.earned?a.icon:'?'}</b><span>{a.name}</span><small>{a.earned?'UNLOCKED':'LOCKED'}</small></button>)}</div></section></div>
 <section className="history-panel"><header><Clock3/><h3>RECENT CREATIVE SESSIONS</h3></header>{sessions.slice(0,4).map(s=><div key={s.id}><b>{s.date}</b><span>{projects.find(p=>p.id===s.projectId)?.title}</span><em>{s.intention}</em><small>{s.minutes} MIN</small></div>)}</section>
 {activeSession&&<div className="active-session-bar"><div className="session-live-dot"/><div className="active-session-copy"><small>CREATIVE SESSION RUNNING</small><b>{projects.find(p=>p.id===activeSession.projectId)?.title}</b><span>{activeSession.intention}</span></div><strong>{elapsedLabel}</strong><button onClick={finishActiveSession}><Square/> FINISH SESSION</button></div>}
 {newWizard&&<NewProjectWizard onSave={p=>{upsert(p);setNewWizard(false)}} onClose={()=>setNewWizard(false)}/>} {editing!==null&&<ProjectEditor project={editing||undefined} onSave={upsert} onClose={()=>setEditing(null)}/>} {sessionProject&&<div className="session-modal"><form onSubmit={e=>{e.preventDefault();beginSession(sessionProject)}}><button type="button" className="modal-close" onClick={()=>setSessionProject(null)}><X/></button><span className="modal-shell">✦</span><small>CREATIVE SESSION</small><h2>WHAT ARE YOU WORKING ON?</h2><label>Choose a project<select value={sessionProject.id} onChange={e=>setSessionProject(projects.find(p=>p.id===e.target.value)||sessionProject)}>{projects.filter(p=>p.status!=='completed'&&p.status!=='graveyard').map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button className="begin-session"><Play/> START SESSION</button><p>No setup. The timer counts up until you finish.</p></form></div>} {selectedAchievement&&<div className="session-modal achievement-modal"><div className={`achievement-card-large ${selectedAchievement.earned?'earned':''}`}><button type="button" className="modal-close" onClick={()=>setSelectedAchievement(null)}><X/></button><span className="achievement-big-icon">{selectedAchievement.earned?selectedAchievement.icon:'?'}</span><small>{selectedAchievement.earned?'ACHIEVEMENT UNLOCKED':'ACHIEVEMENT LOCKED'}</small><h2>{selectedAchievement.name}</h2><p>{selectedAchievement.description}</p><div className="achievement-requirement"><b>HOW TO EARN IT</b><span>{selectedAchievement.requirement}</span></div><button className="achievement-close-button" onClick={()=>setSelectedAchievement(null)}>BACK TO THE ARCHIVE</button></div></div>}</div>
}
