export type ProjectStatus = 'obsession' | 'active' | 'idea' | 'completed' | 'graveyard';
export type Energy = 'low' | 'medium' | 'high';
export type Setup = 'grab-go' | 'light' | 'workstation' | 'takeover';
export interface ProjectTask { id: string; title: string; done: boolean }
export interface ProjectSupply { id?: string; name: string; owned: boolean; cost?: number }
export interface ProjectLogEntry { id: string; date: string; note: string; minutes?: number }
export interface ProjectSession { id: string; projectId: string; date: string; minutes: number; intention: string }
export interface ProjectGalleryItem { id: string; name: string; dataUrl?: string }
export interface CreativeProject {
  id: string; title: string; tagline: string; status: ProjectStatus; category: string;
  energy: Energy; setup: Setup; estimatedMinutes: number; cost: number;
  color: 'pink' | 'blue' | 'coral' | 'gold' | 'seafoam' | 'lavender' | 'kelp' | 'midnight' | 'jelly' | 'seaglass'; icon: string; overview: string; lastTouchedAt?: number; abandonedAt?: number;
  tasks: ProjectTask[]; notes: string[]; gallery: ProjectGalleryItem[]; supplies: ProjectSupply[]; log: ProjectLogEntry[];
}

export const PROJECTS: CreativeProject[] = [
  { id:'cyberdeck',title:'Ally Archive Cyberdeck',tagline:'A tiny offline creative command center',status:'obsession',category:'TECH + ART',energy:'high',setup:'workstation',estimatedMinutes:90,cost:86,color:'pink',icon:'▣',overview:'Turn the pink portable speaker shell into a playful, local-first archive for clothes, ideas, projects, and collected life lore.',tasks:[{id:'c1',title:'Free the two stripped screws',done:false},{id:'c2',title:'Measure the usable interior',done:false},{id:'c3',title:'Prototype Projects tab',done:true},{id:'c4',title:'Choose screen + computer',done:false}],notes:['Keep V11 pixel aquarium language.','Offline first. SQLite can replace sample data later.'],gallery:[{id:'cg1',name:'V11 HOME'},{id:'cg2',name:'SPEAKER SHELL'},{id:'cg3',name:'PROJECTS UI'}],supplies:[{id:'cs1',name:'Portable speaker shell',owned:true},{id:'cs2',name:'Raspberry Pi / mini PC',owned:false,cost:45},{id:'cs3',name:'5–7 inch display',owned:false,cost:32},{id:'cs4',name:'Precision extractor bit',owned:false,cost:9}],log:[{id:'cl1',date:'SEP 12',note:'Mapped achievements and creative stats.',minutes:38},{id:'cl2',date:'SEP 09',note:'Teardown attempt; four screws removed.',minutes:120}] },
  { id:'target-cd',title:'Target Nostalgia Mix',tagline:'The exact soundtrack of little-kid Ally',status:'active',category:'MUSIC',energy:'low',setup:'grab-go',estimatedMinutes:25,cost:4,color:'coral',icon:'●',overview:'Recreate the childhood Target compilation, burn it to CD, and give it artwork pulled from the original memory.',tasks:[{id:'t1',title:'Rebuild track list',done:true},{id:'t2',title:'Burn audio CD',done:true},{id:'t3',title:'Find Guitar Hero childhood photo',done:false},{id:'t4',title:'Design red Target-style label',done:false}],notes:['Possible title: Target Nostalgia.'],gallery:[{id:'tg1',name:'BURNED DISC'},{id:'tg2',name:'COVER IDEA'}],supplies:[{id:'ts1',name:'Blank CD-R',owned:true},{id:'ts2',name:'Jewel case',owned:true},{id:'ts3',name:'Printable label',owned:false,cost:4}],log:[{id:'tl1',date:'SEP 12',note:'Named the mix Target Nostalgia.',minutes:12},{id:'tl2',date:'SEP 09',note:'Burned and finalized the first disc.',minutes:34}] },
  { id:'m5-journal',title:'M5 Pocket Lorebook',tagline:'Tiny pages for big little thoughts',status:'active',category:'JOURNAL',energy:'low',setup:'grab-go',estimatedMinutes:15,cost:18,color:'gold',icon:'▤',overview:'Build a refillable pocket journal full of useful, weird, comforting, and beautiful pages.',tasks:[{id:'m1',title:'Create index',done:true},{id:'m2',title:'Make current obsessions spread',done:false},{id:'m3',title:'Add Nico emergency page',done:false}],notes:['Mix practical lists with collectible-feeling pages.'],gallery:[{id:'mg1',name:'BINDER'}],supplies:[{id:'ms1',name:'M5 binder',owned:true},{id:'ms2',name:'Dot-grid refill',owned:true},{id:'ms3',name:'Mini stickers',owned:true}],log:[{id:'ml1',date:'SEP 09',note:'Brainstormed page ideas.',minutes:22}] },
  { id:'soccer-archive',title:"Dad's Soccer Archive",tagline:'Give the programs a life outside the box',status:'idea',category:'DISPLAY',energy:'medium',setup:'takeover',estimatedMinutes:60,cost:35,color:'blue',icon:'◆',overview:'Create a calm rotating display for decades of soccer programs and stadium cups.',tasks:[{id:'s1',title:'Count and measure programs',done:false},{id:'s2',title:'Choose rotating display zone',done:false}],notes:['Should feel curated, not cluttered. Apothecary-drawer energy.'],gallery:[],supplies:[{id:'ss1',name:'Archival sleeves',owned:false,cost:15},{id:'ss2',name:'Display ledge',owned:false,cost:20}],log:[] },
  { id:'ally-player',title:'Ally CD Player',tagline:'Pink lettering, splashes, stickers, finished',status:'completed',category:'DECOR',energy:'medium',setup:'light',estimatedMinutes:45,cost:8,color:'pink',icon:'★',overview:'Customize the CD player with hand-drawn Ally lettering and the chosen sticker set.',tasks:[{id:'a1',title:'Sketch lettering',done:true},{id:'a2',title:'Outline and fill',done:true},{id:'a3',title:'Add highlights',done:true}],notes:['The oversized lettering was the right call.'],gallery:[{id:'ag1',name:'SKETCH'},{id:'ag2',name:'PINK FILL'},{id:'ag3',name:'FINISHED'}],supplies:[{id:'as1',name:'Pink paint marker',owned:true},{id:'as2',name:'Sticker sheet',owned:true}],log:[{id:'al1',date:'SEP 09',note:'Finished lettering and highlights.',minutes:62}] }
];

export const SAMPLE_SESSIONS: ProjectSession[] = [
  {id:'ss1',projectId:'cyberdeck',date:'SEP 12',minutes:38,intention:'Shape the creative project system'},
  {id:'ss2',projectId:'target-cd',date:'SEP 12',minutes:12,intention:'Name the childhood mix'},
  {id:'ss3',projectId:'ally-player',date:'SEP 09',minutes:62,intention:'Finish lettering + highlights'}
];
